services:
  api:
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    env_file: .env
  postgres:
    image: postgres
    env_file: .env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: